#!/bin/sh
grim $(xdg-user-dir PICTURES)/Screenshots/$(date +'%s.png')
notify-send "Screenshoted!" "Image has been saved" -i $(xdg-user-dir PICTURES)/Screenshots/$(ls $(xdg-user-dir PICTURES)/Screenshots -Art | tail -n 1) 
