#!/bin/sh
hyprctl keyword animation "fadeOut,0,0,default"; geometry=$(slurp -c 88c0d0ff)
hyprctl keyword general:cursor_inactive_timeout 1; sleep 1
grim -g "$geometry" $(xdg-user-dir PICTURES)/Screenshots/$(date +'%s.png')
notify-send "Screenshoted!" "Image has been saved" -i $(xdg-user-dir PICTURES)/Screenshots/$(date +'%s.png')
hyprctl keyword general:cursor_inactive_timeout 0
hyprctl keyword animation "fadeOut,1,7,default"
